name: Tests on network

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: 'Network to run tests'
        options:
        - integration
        - testnet
      python_version:
        type: choice
        description: 'Python version'
        options:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      # ====================== SETUP ====================== #

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config installer.modern-installation false

      - name: Install python 3.9 requirements
        run: |
          poetry export -f requirements.txt --only=py39-dev --without-hashes --output requirements.txt
          pip install -r requirements.txt

      - name: Set up Python ${{ github.event.inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python_version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      # ====================== CONTRACTS v0 ====================== #

      - name: Cache contracts
        id: cache-contracts
        uses: actions/cache@v3
        with:
          path: starknet_py/tests/e2e/mock/contracts_compiled
          key: ${{ runner.os }}-contracts-${{ hashFiles('starknet_py/tests/e2e/mock/contracts', 'poetry.lock') }}

      - name: Compile contracts
        if: steps.cache-contracts.outputs.cache-hit != 'true'
        run: |
          poetry run poe compile_contracts

      # ====================== CAIRO SETUP ====================== #

      - name: Install rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Clone Cairo1 compiler repository
        uses: actions/checkout@v3
        with:
          repository: starkware-libs/cairo
          persist-credentials: false
          ref: v1.0.0-rc0
          path: cairo

      - name: Cache rust dependencies
        id: cache-rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build compiler
        if: steps.cache-rust.outputs.cache-hit != 'true'
        working-directory: ./cairo
        run: |
          cargo build

      - name: Build starknet-compile
        working-directory: ./cairo
        run: |
          cargo run --bin starknet-compile -- --version
          cargo run --bin starknet-sierra-compile -- --version

      - name: Create manifest file
        run: |
          readlink -f cairo/Cargo.toml >> starknet_py/tests/e2e/manifest-path

      # ====================== CONTRACTS v1 ====================== #

      - name: Cache Cairo1 contracts
        id: cache-contracts-v1
        uses: actions/cache@v3
        with:
          path: starknet_py/tests/e2e/mock/contracts_compiled_v1
          key: ${{ runner.os }}-contracts-v1-${{ hashFiles('starknet_py/tests/e2e/mock/contracts_v1', 'poetry.lock') }}

      - name: Compile Cairo1 contracts
        if: steps.cache-contracts-v1.outputs.cache-hit != 'true'
        run: |
          poetry run poe compile_contracts_v1

      # ========================= TESTS ========================= #

      - name: Check circular imports
        run: |
          poetry run poe circular_imports_check

      - name: Run tests
        run: |
          poetry run coverage run -m pytest -v --reruns 2 --only-rerun aiohttp.client_exceptions.ClientConnectorError starknet_py --net=${{ github.event.inputs.network }}

      - name: Generate coverage in XML
        run: |
          poetry run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
